# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Clean Solution
      working-directory: API
      run: dotnet clean
    - name: Restore dependencies
      working-directory: API
      run: dotnet restore
    - name: Build
      working-directory: API
      run: dotnet build --no-restore
    - name: Test
      working-directory: API.Tests
      run: dotnet test --no-build --verbosity normal
    - name: Official SonarQube Scan
    # You may pin to the exact commit or the version.
    # uses: SonarSource/sonarqube-scan-action@bfd4e558cda28cda6b5defafb9232d191be8c203
    - uses: SonarSource/sonarqube-scan-action@v4.2.1
      env:
        SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      with:
        projectBaseDir: ${{ github.workspace }}
        args: >
          -Dsonar.projectKey=n-are-n_E-Commerce
          -Dsonar.organization=Prasad
          -Dsonar.host.url=https://sonarcloud.io
